language: python
sudo: false
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
env:
  - PILLOW_VERSION=2.9.0
  - PILLOW_VERSION=3.0.0
addons:
  apt:
    packages:
      - ubuntu-restricted-extras
      - ffmpeg
    sources:
      # Dependencies to build PIL
      - libfreetype6-dev
      - libjpeg8-dev
      - zlib1g-dev
install:
    - pip install -q Pillow==$PILLOW_VERSION
    - pip install pytest pytest-cov
    - pip install coveralls
    - pip install .
script: py.test --cov sigal --cov-report term-missing tests/
after_success:
    coveralls
notifications:
    irc: "chat.freenode.net#sigal"
